<?php

declare(strict_types=1);

namespace Tests\Unit\Character\Domain\Entities;

use Heart\Character\Domain\Entities\LevelEntity;
use Tests\TestCase;

final class LevelEntityTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_level_entity(): void
    {
        new LevelEntity(1);

        //        foreach (range(0, 11) as $months) {
        //            foreach (range(0, 30) as $days) {
        //                foreach (range(0, 20) as $qtdMensagem) {
        //                    $generatedExperience = $levelEntity->generateVoiceExperience(
        //                        VoiceStatesEnum::Muted,
        //                        true
        //                    );
        //
        //                    dump('exp ganha:' . $generatedExperience);
        //                    dump('level atual: ' . $levelEntity->getLevel());
        //                    dump('level exp atual: ' . $levelEntity->getLevelUpStatus());
        //                }
        //            }
        //        }
        $this->assertTrue(true);
    }
}
