name: Commit Check

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "3.x"
            - "main"
            - "develop"

jobs:
    commit-check:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.sha }}
                  fetch-depth: 0

            - name: Run Commit Check
              uses: commit-check/commit-check-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  message: true
                  branch: true
                  author-name: false
                  author-email: false
                  job-summary: true
                  pr-comments: ${{ github.event_name == 'pull_request' }}
