name: Pre-commit Checks

permissions:
    contents: read

on:
    push:
        branches:
            - "*"
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Python
              uses: actions/setup-python@v5
              id: python-setup
              with:
                  python-version: "3.x"

            - name: Cache pre-commit environments
              uses: actions/cache@v4
              with:
                  path: "~/.cache/pre-commit"
                  key: pre-commit-${{ steps.python-setup.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

            - name: Run pre-commit hooks
              run: pipx run pre-commit run --show-diff-on-failure --color=always --all-files
